name: Build Android C++ Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2

      - name: Build C++ library
        run: |
          # Navigate to lib directory
          cd lib

          # Build for Android (ARM64)
          mkdir build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_NATIVE_API_LEVEL=21
          cmake --build .

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: android-lib
          path: lib/build/my-lib.so
